### PR TITLE
Get rid of import() calls

### PR DESCRIPTION
**Pull request by sustmi**
Hello @pscheit .

I found your https://github.com/pscheit/jparser/tree/namespace branch where you tried to replace `import()` function by namespaces and use.
Your commits however were not really clean. Examples:
In 07cad31cf40d157992a950a11d57a22eb217d0ec you:
- renamed `J_CLASS` constant to `J_class`
- renamed `__CLASS__` constant to `__class__`

Also I do not think that moving all functions into one file was necessary in a0c57875b476e86e03e058a4cca162ddd3389590 .

I tried to do the same by myself in cleaner way.

I am aware that examples and `PLUG/bin/compile` are not working, but I personally would like to get rid of the compiler since there are better tools (eg. https://github.com/ClassPreloader/ClassPreloader ) that can combine PHP files into one without need of special `import()` statements.
Also this tool can be added as Composer dependency and the codebase would be cleaner.

### CODE REVIEW

**Comment by sustmi** [comment]
Another PHP file combiner: ClassCollectionLoader in https://github.com/symfony/class-loader .

**Comment by pscheit** [comment]
hi!
Thanks for the PR but i will no longer support this fork and merge. I can give you the ownership if this helps you in any way?

**Comment by sustmi** [comment]
Well, I currently do not have any other option than this library. So if you do not want to support it any more then please give me the ownership.
Btw, is this yours too https://packagist.org/packages/timwhitlock/jparser ?

**Comment by pscheit** [comment]
jeah no prob.
This is the package from the original author, he said he wont develope the package either.

best regards
Philipp

**Comment by pscheit** [comment]
I would transfer if i could. But your fork does exist (and uses the same name)

I made you collaborator

**Comment by sustmi** [comment]
I do not understand. Is there a problem that I already have a fork with the same name?

If I understand it correctly, you can either give me rights to push to this repository or you can give me rights for the package on Packagist (I don't have an account there currently) and I can change the repository to mine one there.

**Comment by pscheit** [comment]
yep. I cannot transfer because you have a fork.

You can create a new account on packagist and link to your fork/repository. Or you can push/commit into this repository and leave everything as it its.

The packagist entry is yet from me, I just forgot about it :)

**Comment by sustmi** [comment]
I have just created an account on Packagist - username `sustmi`.
I think that it will be best if you could transfer the package to me so that I can decide whether I will continue with the current repository or switch to mine.
Is is possible to change the ownership of the package on Packagist?

**Comment by pscheit** [comment]
yeah, that's a good idea.

Unfortunately no, transfering is not possible. But you can create a new package like sustmi/jparser and I will "abandon" my package in favor of yours.
Just tell me, when you have created it

**Comment by sustmi** [comment]
Yeah, I thought so when I saw that you must enter the repository URL when you are creating the package and Packagist then grabs `composer.json` form there.

Ok, I will create my own package. Thank you for pointing me the right way @pscheit . :)

**Comment by pscheit** [comment]
didnt know about this process before, but good to learn :)
you're welcome! I'm glad that I can help you in the first place

**Pull request closed without merging**
